install.packages("BiocManager", repos='http://cran.us.r-project.org')
library(BiocManager)
install("curl")
install("httr")
install('Seurat')
install('SingleCellExperiment')
install('xml2')
install('tidyverse')
install("dplyr")
install('Matrix')
install('scales')
install('RCurl')
